workflows:
  ios:
    name: Build IPA from Runner.app
    # You can define environment variables and other parameters as needed
    environment:
      vars:
        FLUTTER_ROOT: "/flutter"  # Adjust based on your environment if necessary
    # The build steps to create the IPA
    ios:
      build:
        # Specify the artifact output location
        artifact_output: build/ios/ipa/Runner.ipa
      scripts:
        - name: Build IPA from Runner.app
          script: |
            # Create an IPA from the Runner.app folder
            xcodebuild -exportArchive \
              -archivePath $CI_PROJECT_DIR/build/ios/archive/Runner.xcarchive \
              -exportOptionsPlist $CI_PROJECT_DIR/ios/ExportOptions.plist \
              -exportPath $CI_PROJECT_DIR/build/ios/ipa
